packages:
  - apps/*
  - packages/*

catalog:
  "@biomejs/biome": ^2.3.8
  "@changesets/changelog-github": ^0.5.2
  "@changesets/cli": ^2.29.8
  "@technance/code-style": ^1.5.3
  "@types/lodash-es": ^4.17.12
  "@types/minimist": ^1.2.5
  "@types/node": ^24.10.2
  dotenv: ^17.2.3
  lodash-es: ^4.17.21
  minimist: ^1.2.8
  openai: ^6.10.0
  tsup: ^8.5.1
  tsx: ^4.21.0
  typescript: ^5.9.3
  vitest: ^4.0.15

catalogMode: strict


onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

