name: Publish Any Commit

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - "**"
        tags:
            - "!**"
        paths:
            - "packages/worphling/**"
            - ".github/workflows/preview-release.yml"

env:
    TURBO_TOKEN: ${{ secrets.VERCEL_TECHNANCE_TOKEN }}
    TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    FORCE_COLOR: 3

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: technance-foundation/github-actions/.github/actions/publish-any-commit@main
              with:
                  package-paths: "./packages/worphling"
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
                  pnpm-version: "10.6.5"
