name: Release

on:
    push:
        branches: [release]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    TURBO_TOKEN: ${{ secrets.VERCEL_TECHNANCE_TOKEN }}
    TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    FORCE_COLOR: 3

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            id-token: write
        steps:
            - uses: technance-foundation/github-actions/.github/actions/release@main
              with:
                  cache: pnpm
                  pnpm-version: "10.6.5"
                  pr-base: main
