name: "Smoke Test"

on: push

jobs:
    smoke-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check
              uses: technance-foundation/github-action-check@main
              with:
                  node-version: "20"
                  pnpm-version: "10.6.5"
                  check-command: "pnpm run check"
                  npm-token: ${{ secrets.NPM_TOKEN }}
