name: Telegram notifications

on:
    pull_request:
        types: [opened, ready_for_review]
    pull_request_review:
        types: [submitted]

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Telegram Notify
              uses: invexa-foundation/github-action-telegram-notifications@main
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
