name: Test

on: push

jobs:
    check:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [lts/*]

        name: Test on ${{ matrix.os }} with Node ${{ matrix.node }}

        steps:
            - name: Check
              uses: technance-foundation/github-action-check@main
              with:
                  node-version: "20"
                  pnpm-version: "10.6.5"
                  check-command: "pnpm run test"
                  npm-token: ${{ secrets.NPM_TOKEN }}
