name: Test

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [lts/*]

        name: Test on ${{ matrix.os }} with Node ${{ matrix.node }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  cache: "pnpm"

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm vitest run
